[Variables]

; ==================[User configuration parameters]==================

; --------Language--------

lang=zh-CN

; --------Overall zoom (It is recommended that the accuracy is only controlled to 1 decimal place. Please check the position of the decimal point again before refreshing the skin!!!)--------

zoom=1.0

; --------Display time (True/False. Decide whether to display time)--------

showTime=True

; --------Network speed type (Bandwidth/Speed. Network transmission bandwidth bps and real-time transmission speed B/s)--------

netSpeedType=Speed

; --------Display WAN IP (True/False. Determine the default display status of WAN IP after skin refresh)--------

showWANIP=True



; ==================[Color configuration parameters] (Please do not add transparency value. Please go to "Manage Rainmeter" to adjust skin transparency)==================

; --------Base color--------

fontColour=255,255,255

; --------Information color--------

fontColour2=255,255,0

; --------Bar color--------

fontColour3=0,200,255

; --------Warning color--------

fontColour4=255,0,0
